# Generated by Django 3.2.20 on 2023-08-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
