# Generated by Django 3.2.20 on 2023-08-17 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tasks_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='check',
        ),
    ]
